serverA: serverA.cpp serverB.cpp tcp_tools.cpp client.cpp
	g++ -pthread -o  serverA serverA.cpp tcp_tools.cpp    -g
	g++ -o client client.cpp  tcp_tools.cpp -g
	g++ -o serverB serverB.cpp tcp_tools.cpp -g
	
